name: JasPresents
version: ${project.version}
main: pl.jasmc.presents.Presents
authors: [xDevi]
description: Event na lobb dla Graczy, znajdowanie ukrytych prezentów
depend: [ProtocolLib]
commands:
  prezent: