name: JasPresents
version: ${project.version}
main: pl.jasmc.presents.Presents
authors: [xDevi]
description: Event na lobb dla Graczy, znajdowanie ukrytych prezentów
loadbefore: [Vault]
depend: [Vault,ProtocolLib]
commands:
  prezent: